---
language: php

matrix:
  include:
    - env: TEST_EMBER=true TEST_SAUCE=false TEST_API=true
      php: 7
    - env: TEST_EMBER=false TEST_SAUCE=false TEST_API=true
      php: 5.6
    - env: TEST_EMBER=false TEST_SAUCE=true TEST_API=false
  allow_failures:
    - env: TEST_EMBER=false TEST_SAUCE=true TEST_API=false

dist: trusty
sudo: false

cache:
  yarn: true
  directories:
    - travis_phantomjs

addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
        key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
      - yarn

before_install:
  # update node
  - nvm install 6
  # update phantomjs
  - export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH; if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs && wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 && tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi

install:
  - if $TEST_EMBER || $TEST_SAUCE; then yarn global add bower; fi
  - if $TEST_EMBER || $TEST_SAUCE; then yarn install; fi
  - if $TEST_EMBER || $TEST_SAUCE; then bower install; fi
  # install non development composer requirements for api
  - if $TEST_EMBER || $TEST_SAUCE; then cd api/ && composer install --no-dev && cd ..; fi

before_script:
  # Start a server so we can hit the API from integration tests
  - if $TEST_EMBER; then ember server --live-reload=false; fi &
  # wait for the server to be started
  - if $TEST_EMBER; then sleep 10; fi
  # http://php.net/manual/de/ini.core.php#ini.always-populate-raw-post-data
  - if $TEST_API; then echo 'always_populate_raw_post_data = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  # create a sauce tunnel
  - if $TEST_SAUCE; then ember sauce:connect; fi

script:
  # run frontend and integration tests
  - if $TEST_EMBER; then yarn test; fi
  # test against different browsers using sauce lab
  # we can not run the integration tests against api cause api is not available to test instance running at sauce lab
  # therefore we only run acceptance tests by filter
  # to do so we can not just add the launcher to testem ci configuration
  - if $TEST_SAUCE; then ember test --launch='SL_chrome,SL_firefox,SL_edge,SL_ie,SL_safari' --test-port 8080 --filter 'Acceptance |'; fi
  # install development requirements for api to run api tests
  # not be done in install section cause otherwise integration tests would not fail
  # if api needs an dependency in production which is specified as development dependency
  - if $TEST_API; then cd api/ && composer install && cd ..; fi
  # run api tests with composer
  - if $TEST_API; then cd api/ && ./vendor/bin/codecept run && cd ..; fi

after_script:
  # destroy the sauce tunnel
  - if $TEST_SAUCE; then ember sauce:disconnect; fi
