---
language: php
php:
  - 5.6
  - 7

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install
  - cd api/ && composer install --no-dev && cd .. # install non development composer requirements for api

before_script:
  - ember server --live-reload=false & # Start a server so we can hit the fake API from integration tests
  - sleep 10 # wait for the server to be started
  - echo 'always_populate_raw_post_data = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini # http://php.net/manual/de/ini.core.php#ini.always-populate-raw-post-data
  - npm list # list all installed npm packages

script:
  - npm test # run frontend and integration tests
  - cd api/ && composer install && cd .. # install development requirements for api to run api tests
  - cd api/ && ./vendor/bin/codecept run && cd .. # run api tests with codeception
